### PR TITLE
fix: Fix --yarn-workspace with Yarn 3.

### LINKED ISSUE #180: scip-typescript fails to index Yarn workspaces with Yarn 3
Using the `--yarn-workspaces` flag triggers an invocation to ` yarn --silent --json workspaces info`. However, `workspaces info` doesn't seem to be available with Yarn 3.2.3. It is available with Yarn 1.22.19.

### PR DESCRIPTION
**Pull request by varungandhi-src**
Fixes #180.

### Test plan

Manually tested against the Sourcegraph monorepo with Yarn 3 which seems to have been made the default around Sept 1 (http://github.com/sourcegraph/sourcegraph/pull/39728). The last scip-typescript upload for sg/sg was on Sept 2 (https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/code-graph/uploads?query=scip-typescript), so it seems like this job has been broken since then.

### CODE REVIEW

**Review by olafurpg — COMMENTED** [review]
What's the relationship with this PR here https://github.com/sourcegraph/scip-typescript/pull/168? We already support Yarn v3 with `--yarn-berry-workspaces`

**Comment by varungandhi-src** [comment]
Hmm, I didn't know what Yarn Berry was. I guess it is a little weird to have two flags instead of one...

**Comment by varungandhi-src** [comment]
Looks like I just reimplemented that PR but in a different function. 🤦🏽 

I thought Yarn Berry was some different fork of Yarn or something that we added special support for.

**Comment by olafurpg** [comment]
cc/ @valerybugakov any opinions about having a separate flag for Yarn v3?

**Comment by valerybugakov** [comment]
@olafurpg, I don't see a reason for having a separate flag for Yarn v3 if we already have `--yarn-berry-workspaces`. There's the next major `yarn` version on the horizon, so it makes sense to bind the flag to the package-manager workspaces protocol, not the package-manager version.

**Comment by olafurpg** [comment]
@valerybugakov I meant, should we aim to consolidate `--yarn-workspaces` and `--yarn-berry-workspaces`? Varun implemented this PR without realizing we already support v3 because the `--yarn-berry-workspaces` name is not self-explanatory for somebody who is not intimately familiar with Yarn development

**Comment by valerybugakov** [comment]
> should we aim to consolidate `--yarn-workspaces` and `--yarn-berry-workspaces`?

I see. Then yes, hiding this detail from the user would be nice 👍

**Comment by varungandhi-src** [comment]
OK, looks like we're in agreement then. I've removed the code duplication between the newly added implementation and the previously added one.

File: src/main.ts [hunk 1]
```diff
@@ -200,51 +200,57 @@ function defaultCompilerOptions(configFileName?: string): ts.CompilerOptions {
...
-  // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
-  for (const key of Object.keys(json)) {
-    const location = 'location'
-    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
-    if (json[key][location] !== undefined) {
-      // eslint-disable-next-line @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
-      result.push(path.join(directory, json[key][location]))
+  if (yarnVersion === 'tryYarn1') {
+    try {
+      yarn1WorkspaceInfo()
```
Comment (olafurpg) [inline src/main.ts]: Do we flip the order here?

**Review by olafurpg — APPROVED** [review]
LGTM 👍🏻

File: src/main.ts [hunk 2]
```diff
@@ -200,51 +200,57 @@ function defaultCompilerOptions(configFileName?: string): ts.CompilerOptions {
...
+    } catch {
+      yarn2PlusWorkspaceInfo()
```
Comment (varungandhi-src) [inline src/main.ts]:
```suggestion
      yarn2PlusWorkspaceInfo()
    } catch {
      yarn1WorkspaceInfo()
```

**Review by olafurpg — COMMENTED** [review]
Also worth updating the readme https://github.com/sourcegraph/scip-typescript#index-a-typescript-project-using-yarn-workspaces
